[build]
  base = "server"
  functions = "netlify/functions"
  publish   = "../client/dist"  # relative to /server

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true