[build]
  base = "."
  functions = "server/netlify/functions"
  publish = "client/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  
[functions."server"]
  included_files = ["firebase-service-account.json"]