[build]
  functions = "netlify/functions"
  publish = "public"  # adjust if your frontend build output differs

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
